name: Build dbt environment
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: fishtownanalytics/dbt:1.0.0
                shell: bash
                run: |
                  pwd
                  dbt --version
                  pwd
                  ls /home/runner/work/
