name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: addnab/docker-run-action@v3
    - name: Build the Docker image for dbt
      with:
        image: fishtownanalytics/dbt:1.0.0
        shell: bash
        run: |
          echo "first line"
          echo "second line"
