version: 2

sources:
  - name: covid
    schema: williams_dev
    database: "{{ var('env') }}"
    tables:
      - name: _airbyte_raw_covid_epidemiology
  - name: juvare
    schema: dbo
    database: wedb_9
    tables:
      - name: boards
      - name: tables
      - name: table_1
      - name: incidents
      - name: shelters
